### ISSUE TITLE
[BE] DB 이모지 삽입 관련 조사

### ISSUE THREAD

**Issue by Dae-Hwa** [Lia316/issue-tracker#12]

**Comment by Dae-Hwa** [comment]
https://www.h2database.com/html/advanced.html#standards_compliance
h2는 따로 설정안해줘도 다 지원해준답니다.

mysql 설정할때 따로 테스트 하면서 진행해야 할 것 같아요

**Comment by ghost** [comment]
이슈 close하겠습니다
