### ISSUE TITLE
[FE] 할일 Backlog

### ISSUE THREAD

**Issue by jeonyeonkyu** [Lia316/issue-tracker#2]
# FE 할일 Backlog

> Beemo의 하루 === 12시간
>
> 에자일 하게 일한다는것 === 시간을 써두긴 했지만 언제든 바뀔 수 있다
>
> 6월 7일 월요일 시작~ 

### 상태관리용 라이브러리 만들기

- [ ] recoil 만들어보기  

  - [x] 구상 >  8시간 예상

  - [x] 불필요한 리렌더링 방지기능 (recoil 방식)   >  8시간 예상
  - [ ] useRecoilValue, useRecoilState와 같은 메서드 제공   >  3시간 예상
  - [ ] 동일한 url 캐싱하기   >  4시간 예상

> 총 23시간 예상 
>
> 6월 9일 수요일까지 하기

### 함수형 프로그래밍을 활용한 데이터 변경

- [x] pipe, compose 다시 분석 

> 총 3시간 예상
>
> 6월 10일 ~

### 1페이지 - 시작 (설계하기)

- [x] react-router 등 설계하기 - 클래스 다이어그램 만들기   >  6시간 예상
- [x] 프로젝트 설정하기 (create-react-app 사용)

> 6시간 예상
>
> 6월 10일 까지

### 2페이지 - 로그인 페이지

- [ ] 로그인 github Oauth 연동   >  하루예상 (안해본 기술..)
  - [ ] 로그인 UI 만들기   >  2시간 예상
- [ ] 선택적 레이아웃 로그인    >  6시간 예상 (마지막으로 미뤄두자)

> 총 20시간 예상
>
> 6월 11일 ~ 주말까지

### 3페이지 - 이슈 목록

- [x] 이슈 목록 UI 만들기   >  6시간 예상
- [x] 탭 UI 만들기 (레이블탭, 마일스톤 탭)   >   2시간 예상 - UI는 8,9 페이지에서..
- [ ] 상세화면 페이지로 이동하기   >  2시간 예상- UI는 7페이지에서.. 

> 총 10시간 예상
>
> 6월 14일 까지

### 4페이지 - 이슈목록 / 필터

- [x] 필터 목록 띄우기  -  머티리얼 UI 사용   >  2시간 예상
- [x] 필터 목록 닫기   >  2시간 예상
- [ ] 필터 목록에 따른 이슈띄우기   >  8시간 예상 
- [ ] 필터 기능   >   6시간

> 총 하루 반 예상
>
> 6월 16일 까지

### 5페이지 - 이슈목록 / 다중 선택

- [x] 체크박스 기능(이슈 다중선택, 전체선택,해제)   >  3시간 예상
- [ ] 상태 수정 팝업, 이슈 열기, 닫기 기능   >  8시간 예상 

> 총 11시간 예상
>
> 6월 17일까지

### 6페이지 - 새로운 이슈 작성

- [x] 이슈작성 페이지 UI    >  3시간 예상
- [ ] 파일첨부기능   >   5시간 예상
- [ ] 담당자, 레이블, 마일스톤 추가하기 기능   >  3시간 예상

> 총 11시간 예상

### 7페이지 - 이슈상세

- [x] 이슈상페 페이지 UI   >  6시간 예상
- [ ] 데이터 뿌려주기   >  6시간 예상

> 총 12시간 예상
>
> 6월 18일 까지

### 8페이지 - 레이블 목록

- [x] 레이블 목록 UI   >  3시간 예상
- [x] 레이블 목록 데이터 뿌려주기   >  2시간 예상
- [ ] 레이블 추가 기능   >  2시간 예상
- [ ] 편집, 삭제 기능   >  3시간 예상
- [ ] 레이블 이름, 색 등록   >  2시간 예상

> 총 12시간 예상
>
> 6월 20일 주말까지

### 9페이지 - 마일스톤 목록

- [ ] 마일스톤 데이터 뿌려주기   >  2시간 예상
- [ ] 마일스톤 추가 기능   >  2시간 예상
- [ ] 편집, 삭제 기능   >  3시간 예상

> 총 7시간 예상
>
> 6월 21일 까지

### 추가 기능

- [ ] history 관리 
- [ ] 로딩중 스켈레톤 UI 적용하기
- [ ] README.md 관리하기
- [ ] 이슈 peiview 기능

> 위의 기간은 예상 기간이므로 에자일하게 시간 조절하기~

**Comment by jeonyeonkyu** [comment]
세부기획서가 또 있어서 25일까지 다 못할 수 도 있겠다는 생각이듬
세부기획서에 따른 일정은 패스~

**Comment by jeonyeonkyu** [comment]
- 컴포넌트 구상 다이어그램

![image](https://user-images.githubusercontent.com/61257242/121278231-26f0b880-c90d-11eb-9956-7f453ba83901.png)
[다이어그램 링크](https://app.diagrams.net/#G1ZzI9fMRlGuvPmKKMQsl9Fx-mh4PlpKH9)

- 중복된 부분이 많은데 어떻게 처리할지.. HOC를 도입해야하나? 안쓴다고 하던데..
- 고민해봐야겠다

**Comment by ghis22130** [comment]
와우 엄청 잘 정리해 두셨네요!

**Comment by jeonyeonkyu** [comment]
> 와우 엄청 잘 정리해 두셨네요!

감사합니다 ㅎㅎ 👍

**Comment by jeonyeonkyu** [comment]
말도 안되는 계획이었습니다
