### ISSUE TITLE
레이블, 마일스톤 카운트 의견 부탁드립니다.

### ISSUE THREAD

**Issue by Dae-Hwa** [Lia316/issue-tracker#28]
```
{"레이블 카운트" : 3},
{"마일스톤 카운트" : 2} 
```
![image](https://user-images.githubusercontent.com/24666330/121349810-e6bd2480-c964-11eb-8010-ff7ef8704fe6.png)

1. 별도의 api로 나눈다.
    1. 각각 다른 api로 만든다
    2. 두 가지를 한 가지 api로 만든다.
2. 각 API에 포함시킨다.

**Comment by ghost** [comment]
제 의견은 
- 별도로 나눈다 -> 각각 다른 api로 만든다. 가 좋을거 같습니다.

**Comment by Lia316** [comment]
저도 1-1) `각각 다른 api`가 좋습니다

**Comment by jeonyeonkyu** [comment]
저도요 ㅎㅎ 
별로도 나누는게 수월해보입니다~~ 👍

**Comment by ghis22130** [comment]
늦엇지만 저도 1-1이 좋습니다 ㅎ

**Comment by Dae-Hwa** [comment]
모두 의견 감사합니다! 이슈 닫겠습니다
