### ISSUE TITLE
[iOS] 이슈목록 화면 관련 객체들에 대한 Test

### ISSUE THREAD

**Issue by ghis22130** [Lia316/issue-tracker#49]
- 이슈 목록 화면에 관련된 객체들에 대한 Test Code 를 작성하고 확인한다.

**Comment by Lia316** [comment]
- [x] 이슈뷰모델 생성
- [x] 이슈뷰모델 이슈 프로퍼티 삭제
- [x] hexString → UIColor 변환

**Comment by Lia316** [comment]
테스트하는 공부도 하고, 헥사 컬러에 관한 유의미한 결과를 얻음
