### ISSUE TITLE
[iOS] 편집 모드 전환 시 animation 안 나타나는 버그

### ISSUE THREAD

**Issue by Lia316** [Lia316/issue-tracker#67]
### 문제 상황

`tableView.setEditing(_ editing: Bool, animated: Bool)`
이 코드에서 animated: true 를 해줘도 animation 이 동작하지 않는다

뭐가 문제인지 모르겠다...

찾아본 바로는, 
- 애니메이션이 되는 게 정상이다
- 스택오버플로우의 오래된 질문이 있긴하나 도움이 되지 않았다

**Comment by ghis22130** [comment]
어제 리아가 보여준 화면에서는 애니메이션 동작 했던 것 같은데..... 원래는 동작했다가 어느 순간부터 안되는건가요? 아님 원래 동작을 안했었나요..?

**Comment by Lia316** [comment]
처음부터 동작하지 않았습니다 ㅠㅠ
매우 의문스러워요

**Comment by ghis22130** [comment]
해결했지요

**Comment by Lia316** [comment]
덤바의 활약으로 해결
- `isSelected`가 이미 변경되었던 문제
