### ISSUE TITLE
[iOS] 이슈 목록 화면 - BackgroundProperty

### ISSUE THREAD

**Issue by ghis22130** [Lia316/issue-tracker#75]
MainStoryboard 에서 Background  View 가 존재하는데 앱 실행에 이 View가 실제로 사용이 되는지 궁금합니다!

**Comment by Lia316** [comment]
넵 말 그대로 배경화면 색상을 주는 뷰입니다.
<img src = "https://user-images.githubusercontent.com/73650994/121846171-8c83e100-cd21-11eb-9848-4667d77f5336.png" width = "250">

**Comment by ghis22130** [comment]
아하!! 알겠습니다 이슈 클로즈할께용ㅎ
